### ISSUE TITLE
Release v2.11.0

### ISSUE THREAD

**Issue by qkdreyer** [commitizen/cz-cli#569] opened 2018-09-28 15:36 UTC
Are you guys planning to release a new version soon ?
I'd like to get the dependencies update commits.

https://github.com/commitizen/cz-cli/compare/v2.10.1...master

**Comment by jimthedev** [comment] 2018-09-28 15:39
We are working through it on the modernize-part-deux branch. We had
everything updated in modernize branch but it had some windows regressions.
In the future we will catch these sooner using MS dev ops instead of
appveyor.

-- 
Jim ForCy

**Comment by jimthedev** [comment] 2018-10-01 14:54
FYI 3.0.0 has been released but please be aware that commitizen init seems to be having some issues resolving paths.

**Closed by jimthedev** 2018-10-01 14:54 UTC
