### ISSUE TITLE
Can't select change type with arrow keys

### ISSUE THREAD

**Issue by BarryThePenguin** [commitizen/cz-cli#10] opened 2015-09-10 06:10 UTC
Just a heads up I am experiencing the following on WIndows 8.1 SBoudrias/Inquirer.js#266

node -v 4.0.0

cc @kentcdodds

**Comment by kentcdodds** [comment] 2015-09-10 12:51
Hmmm. That's annoying :-( I guess you'll just have to hand-craft your commits until that bug gets fixed...

**Comment by BarryThePenguin** [comment] 2015-10-19 01:57
I followed the rabbit hole and found nodejs/node#2996

**Comment by jimthedev** [comment] 2015-10-19 03:02
Interesting. Thanks for finding that. Is this something we should add to docs until it gets resolved?

**Comment by kentcdodds** [comment] 2015-10-19 03:34
Seems like a good idea to me. I'm thinking about adding it to my contributing docs... Even better: detect the node version and os and give a warning if this could be a problem.

**Comment by jimthedev** [comment] 2015-10-28 16:40
Quick update. Looks like the node issue is still open and they're trying to figure out a fix that doesn't introduce a regression. Until then, we wait. :)

**Comment by jimthedev** [comment] 2015-11-09 14:51
Update: It looks like the change that started causing this issue has been reverted so I'd imagine it is available in nightlies: https://github.com/nodejs/node/commit/af46112828cb28223050597f06b5e45a659e99d6

But I'm not sure when it will get released and perhaps more importantly when it will get back ported to Node 4 LTS.

**Comment by jimthedev** [comment] 2015-11-16 22:01
Quick update: This will be released in the next Node.js versions on both the 4.x and 5.x branches. I'm going to close the issue for now since it is merged and out of the control of this repo. 

More info:
https://github.com/eslint/eslint/issues/3880

**Comment by ocombe** [comment] 2015-11-28 17:40
I just had the problem on windows, it still doesn't work with the last 4.x version (4.2.2), but it works with the last 5.x version (5.1.0), so that's all good :)

**Comment by jimthedev** [comment] 2015-11-29 01:25
Thanks for the confirmation @ocombe. I know there are some security patches being worked into older versions so perhaps it is taking a bit longer to get this in to those. At any rate, it is good to know it is fixed in 5.x!!!

**Comment by clearbug** [comment] 2016-02-26 08:07
I also met this .How do you solve this problem? @BarryThePenguin

**Comment by egoroof** [comment] 2016-02-29 16:02
@clearbug see https://github.com/nodejs/node/issues/5384. Now it's a new problem.

**Comment by jimthedev** [comment] 2016-04-28 15:46
I re-opened this since as @egoroof stated, this continues to be a node or windows issue. Latest update from https://github.com/nodejs/node/issues/5384 is that it might be an issue with windows itself. Basically it is tricky to fix because it presents as a race condition.

**Comment by simonwjackson** [comment] 2016-05-15 08:26
Commitizen is essential to my dev workflow, so I made a **quick hack** so I could just type out the feature (rather than use arrow keys).

This gets the job done, but i hope the nodejs guys get this sorted out.

simonwjackson/cz-conventional-changelog@c408892e6fda003f70fdcadcd17c277a75b7d82c

**Comment by BarryThePenguin** [comment] 2016-05-16 23:03
Looks like there's another potential fix coming through libuv/libuv#852

**Comment by Mouvedia** [comment] 2016-09-29 08:32
Both are closed.

**Comment by meszaros-lajos-gyorgy** [comment] 2017-05-29 13:17
I experience the same on Windows 7 using the git bash from the latest Git install (mintty 2.7.3 x86_64-pc-msys). It works fine in windows cmd.

**Comment by wcalebgray** [comment] 2017-08-16 18:25
Seeing this on Windows 10 as well (mintty 2.7.7 x86_64-pc-msys)

**Comment by xetra11** [comment] 2017-09-01 12:00
Having this issue, too. CMD and GIT BASH both deny the arrow movement

**Comment by yanfeipeng** [comment] 2018-05-02 07:40
window cmd can work, but git bash mintty not
![image](https://user-images.githubusercontent.com/12102322/39511162-0d6eeef2-4e1f-11e8-8c88-de3872f246c5.png)

**Comment by sschmidTU** [comment] 2018-07-09 16:34
**Workaround**
In my Git Bash keypresses are actually executed invisibly, they just don't cause a rendering refresh. So e.g. for a refactor, after git cz i press down arrow 4 times and hit enter, and it shows refactor as type of change.
Found this after a lot of research subtly hidden here, comment from March 3 2018.

**Closed** 2021-03-06 05:17 UTC
Labels: bug, dependency related
