### ISSUE TITLE
"No files added" Error not trapped

### ISSUE THREAD

**Issue by plroebuck** [commitizen/cz-cli#480] opened 2018-05-11 17:01 UTC
<https://github.com/commitizen/cz-cli/blob/40d8dab1649fc10cbcfaed91944936817bb74348/src/cli/strategies/git-cz.js#L56>

If your forget to add files first, you get this:
```console
$ git-cz
/usr/local/lib/node_modules/commitizen/dist/cli/strategies/git-cz.js:87
      throw new Error('No files added to staging! Did you forget to run git add?');
      ^

Error: No files added to staging! Did you forget to run git add?
    at /usr/local/lib/node_modules/commitizen/dist/cli/strategies/git-cz.js:87:13
    at /usr/local/lib/node_modules/commitizen/dist/commitizen/staging.js:25:5
    at ChildProcess.exithandler (child_process.js:267:7)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:567:12)
$
```

This is (for me anyways and expect others as well) a common occurrence, usually from iterating too quickly through my cmdline history. So from my standpoint, a predictable minor error. As such, a stack trace seems a bit much.

Any good reason this couldn't trapped and reduced to `console.error(err.message);`? 
Maybe add `code` to error instance and check for it at CLI application bounds.

**Comment by plroebuck** [comment] 2018-05-17 13:52
Sorry, missed #473 which requested same... Knew there had to be other people with same problem :)

**Comment by LinusU** [comment] 2018-05-17 13:56
Closing as duplicate of #473

PRs welcome 🚀

**Closed by LinusU** 2018-05-17 13:56 UTC
