### ISSUE TITLE
NPM Warning

### ISSUE THREAD

**Issue by TJProgrammer** [commitizen/cz-cli#716] opened 2020-03-26 02:18 UTC
Hello!

The pakage `core-js` needs to be updated ...
```
warning: commitizen > cz-conventional-changelog > @commitlint/load > babel-runtime > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
```

**Comment by bajtos** [comment] 2020-04-06 12:11
I think this is a duplicate of #715

**Closed** 2020-04-13 22:48 UTC
